### ISSUE TITLE
After using this asset Remote Config in console does not work

### ISSUE THREAD

**Issue by mirgan** [FirebaseExtended/unity-solutions#21]
After using this asset Remote Config in console does not work.
Alway display error update:
"A new version of the configuration was saved while you were editing. Choosing to force publish will overwrite those changes."
Rebooting Unity or computer does not help.

**Comment by dzlier-gcp** [comment]
Could you post a screenshot of what you are seeing in the console? I have not seen this issue, always been able to edit from both. Do you have pending console changes you could reset?

**Comment by mirgan** [comment]
I checked this morning and it worked. Maybe it was a failure in Firebase ... Thanks!

**Comment by dzliergaard** [comment]
Good to hear. Don't hesitate to reach out if you have other issues, or think of feature requests!
